server:
  port: 9090
spring:
  config:
    activate:
      on-profile: local
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: lemon-api
      password: 1234
---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod
