server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lemon
    username: lemon-api
    password: 1234
  jooq:
    sql-dialect: mariadb
  devtools:
    livereload:
      enabled: true
    restart:
      quiet-period: 600ms
decorator.datasource.p6spy.enable-logging: true
logging:
  level:
    root: INFO
    com.sweeti.lemon.domain: INFO
    org.hibernate:
      type.descriptor.sql: WARN
      sql: WARN
---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod
